### ISSUE TITLE
Update react native version to latest

### ISSUE THREAD

**Issue by roshangm1** [roshangm1/wwktm-mobile#60]

**Comment by JacobRReed** [comment]
Assign this to me, would you like me to update all packages or just react-native packages?

**Comment by bruno-edo** [comment]
I'll do this one.

**Comment by roshangm1** [comment]
@bruno-edo I will assign this task to you. Make sure to upgrade all the dependency packages. 
Use this tool to see the changes and make changes accordingly.

https://react-native-community.github.io/upgrade-helper/?from=0.60.0&to=0.61.1

**Comment by bruno-edo** [comment]
Alright.

Just gonna test the build tomorrow on my macbook and I think it's done.

Left the PR with a `WIP`, but if you wanna test if it builds correctly and give the green light go ahead :)

**Comment by roshangm1** [comment]
Great!! I will test it today.

**Comment by roshangm1** [comment]
PR #61 has been merged and is working fine. Closing this now.
